const ROUTES = {
  GUEST_HOME: '/',
  HOME: '/home',
  LOGIN: '/login',
  REGISTER: '/register',
  CONFIRM_EMAIL: '/confirm-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESEND_PASSWORD: '/resend-password',
  SUCCESS_CONFIRM: '/email-success-confirm',
  PROFILE: '/profile/:userId',
  PROFILE_ME: '/profile',
  WALLET: '/my-wallet',
  FEEDBACK: '/feedback',
  TRIAL_FREE: '/trial',
  REVIEW: '/review/:id',
  HISTORY_TOUR: '/history-tour',
  CONTACT: '/contact',
  FAQ: '/faq',
  BLOG: '/blog',
  BLOG_DETAILS: '/blog/:id',
  FORUM: '/forum',
  FAVORITES: '/favorites',
  TOUR_DETAIL: '/tour-detail/:id',
  TOUR_AUDIO: '/tour-audio/:id',
  AUDIO_PLAYER: '/audio-player',
  CONFESSION: '/confession',
  MESSAGE: '/message/t/:id',
  SERVICES: '/services',
  CHECKOUT: '/checkout',
  NOTIFICATION: '/notification',
  CHARACTER: '/character/:id',
  ADMIN: {
    DASHBOARD: '/admin',
    REVENUE: '/admin/revenue',
    MEMBER: '/admin/member',
    TOUR: '/admin/tour',
    FAQ: '/admin/faq',
    FEEDBACK: '/admin/feedback',
    CONTACT: '/admin/contact',
  },
  NOT_FOUND: '*'
};

export default ROUTES;